---
- name: Set Finder settings
  osx_defaults:
    domain: "com.apple.finder"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - key: "NewWindowTarget"
      type: "string"
      value: "PfLo"
    - key: "NewWindowTargetPath"
      type: "string"
      value: "file://{{ ansible_env.HOME }}/"
    - key: "ShowExternalHardDrivesOnDesktop"
      type: "bool"
      value: "true"
    - key: "ShowHardDrivesOnDesktop"
      type: "bool"
      value: "true"
    - key: "ShowMountedServersOnDesktop"
      type: "bool"
      value: "true"
    - key: "ShowRemovableMediaOnDesktop"
      type: "bool"
      value: "true"
    - key: "ShowPathbar"
      type: "bool"
      value: "true"
    - key: "QLEnableTextSelection"
      type: "bool"
      value: "true"
    - key: "_FXShowPosixPathInTitle"
      type: "bool"
      value: "true"
    - key: "FXDefaultSearchScope"
      type: "string"
      value: "SCcf"
    - key: "FXEnableExtensionChangeWarning"
      type: "bool"
      value: "false"
    - key: "FXPreferredViewStyle"
      type: "string"
      value: "Nlsv"
    - key: "EmptyTrashSecurely"
      type: "bool"
      value: "true"
    - key: "WarnOnEmptyTrash"
      type: "bool"
      value: "false"

- name: Set safari settings
  osx_defaults:
    domain: "com.apple.Safari"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - key: "UniversalSearchEnabled"
      type: "bool"
      value: "false"
    - key: "SuppressSearchSuggestions"
      type: "bool"
      value: "true"
    - key: "WebKitTabToLinksPreferenceKey"
      type: "bool"
      value: "true"
    - key: "AutoOpenSafeDownloads"
      type: "bool"
      value: "false"
    - key: "ShowFavoritesBar"
      type: "bool"
      value: "false"
    - key: "ShowSidebarInTopSites"
      type: "bool"
      value: "false"
    - key: "FindOnPageMatchesWordStartsOnly"
      type: "bool"
      value: "false"

- name: Set Dock settings
  osx_defaults:
    domain: "com.apple.dock"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - key: "autohide-delay"
      type: "float"
      value: "0.1"
    - key: "mouse-over-hilite-stack"
      type: "bool"
      value: "true"
    - key: "tilesize"
      type: "int"
      value: "36"
    - key: "show-process-indicators"
      type: "bool"
      value: "true"
    - key: "expose-animation-duration"
      type: "float"
      value: "0.1"
    - key: "launchanim"
      type: "bool"
      value: "false"
    - key: "mineffect"
      type: "string"
      value: "scale"
    - key: "minimize-to-application"
      type: "bool"
      value: "true"
    - key: "show-process-indicators"
      type: "bool"
      value: "true"
    - key: "persistent-apps"
      type: "array"
      value: ""
    - key: "expose-group-by-app"
      type: "bool"
      value: "false"
    - key: "dashboard-in-overlay"
      type: "bool"
      value: "true"
    - key: "showhidden"
      type: "bool"
      value: "true"

- name: Set global settings
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - key: "AppleShowScrollBars"
      type: "string"
      value: "WhenScrolling"
    - key: "NSWindowResizeTime"
      type: "float"
      value: "0.001"
    - key: "NSTableViewDefaultSizeMode"
      type: "int"
      value: "2"
    - key: "NSNavPanelExpandedStateForSaveMode"
      type: "bool"
      value: "true"
    - key: "NSNavPanelExpandedStateForSaveMode2"
      type: "bool"
      value: "true"
    - key: "PMPrintingExpandedStateForPrint"
      type: "bool"
      value: "true"
    - key: "PMPrintingExpandedStateForPrint2"
      type: "bool"
      value: "true"
    - key: "NSDocumentSaveNewDocumentsToCloud"
      type: "bool"
      value: "false"
    - key: "NSTextShowsControlCharacters"
      type: "bool"
      value: "true"
    - key: "NSAutomaticQuoteSubstitutionEnabled"
      type: "bool"
      value: "false"
    - key: "com.apple.mouse.tapBehavior"
      type: "int"
      value: "1"
    - key: "AppleKeyboardUIMode"
      type: "int"
      value: "3"
    - key: "AppleLanguages"
      type: "array"
      value: "en"
    - key: "AppleLocale"
      type: "string"
      value: "en_US@currency=USD"
    - key: "AppleMeasurementUnits"
      type: "string"
      value: "Centimeters"
    - key: "AppleMetricUnits"
      type: "bool"
      value: "true"
    - key: "AppleFontSmoothing"
      type: "int"
      value: "2"
    - key: "NSAutomaticDashSubstitutionEnabled"
      type: "bool"
      value: "false"
    - key: "ApplePressAndHoldEnabled"
      type: "bool"
      value: "false"
    - key: "KeyRepeat"
      type: "float"
      value: "1"
    - key: "InitialKeyRepeat"
      type: "int"
      value: "20"
    - key: "AppleShowAllExtensions"
      type: "bool"
      value: "true"
    - key: "NSAutomaticSpellingCorrectionEnabled"
      type: "bool"
      value: "false"

- name: Set some other settings
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - domain: "/Library/Preferences/com.apple.SoftwareUpdate"
      key: "AllowPreReleaseInstallation"
      type: "bool"
      value: "false"
    - domain: "com.apple.ActivityMonitor"
      key: "OpenMainWindow"
      type: "bool"
      value: "true"
    - domain: "com.apple.ActivityMonitor"
      key: "ShowCategory"
      type: "int"
      value: "0"
    - domain: "com.apple.ActivityMonitor"
      key: "SortColumn"
      type: "string"
      value: "CPUUsage"
    - domain: "com.apple.ActivityMonitor"
      key: "SortDirection"
      type: "int"
      value: "0"
    - domain: "com.apple.TimeMachine"
      key: "DoNotOfferNewDisksForBackup"
      type: "bool"
      value: "true"
    - domain: "com.apple.LaunchServices"
      key: "LSQuarantine"
      type: "bool"
      value: "false"
    - domain: "com.apple.print.PrintingPrefs"
      key: "Quit When Finished"
      type: "bool"
      value: "true"
    - domain: "com.apple.screensaver"
      key: "askForPassword"
      type: "int"
      value: "1"
    - domain: "com.apple.screensaver"
      key: "askForPasswordDelay"
      type: "int"
      value: "0"
    - domain: "/Library/Preferences/com.apple.windowserver"
      key: "DisplayResolutionEnabled"
      type: "bool"
      value: "true"
    - domain: "com.apple.dashboard"
      key: "mcx-disabled"
      type: "bool"
      value: "true"
    - domain: "com.apple.NetworkBrowser"
      key: "BrowseAllInterfaces"
      type: "bool"
      value: "true"
    - domain: "com.apple.desktopservices"
      key: "DSDontWriteNetworkStores"
      type: "bool"
      value: "true"
    - domain: "com.apple.desktopservices"
      key: "DSDontWriteUSBStores"
      type: "bool"
      value: "true"
    - domain: "com.apple.screencapture"
      key: "location"
      type: "string"
      value: "{{ ansible_env.HOME }}/Desktop"
    - domain: "com.apple.screencapture"
      key: "type"
      type: "string"
      value: "png"
    - domain: "com.apple.BluetoothAudioAgent"
      key: "Apple Bitpool Min (editable)"
      type: "int"
      value: "40"
    - domain: "com.apple.driver.AppleBluetoothMultitouch.trackpad"
      key: "Clicking"
      type: "int"
      value: "1"
    - domain: "com.apple.SoftwareUpdate"
      key: "ScheduleFrequency"
      type: "int"
      value: "1"
    - domain: "com.apple.SoftwareUpdate"
      key: "AutomaticCheckEnabled"
      type: "bool"
      value: "true"
    - domain: "com.apple.SoftwareUpdate"
      key: "AutomaticDownload"
      type: "int"
      value: "1"
    - domain: "com.apple.SoftwareUpdate"
      key: "CriticalUpdateInstall"
      type: "int"
      value: "1"
    - domain: "com.apple.commerce"
      key: "AutoUpdate"
      type: "bool"
      value: "true"
    - domain: "com.apple.ImageCapture"
      key: "disableHotPlug"
      type: "bool"
      value: "true"

- name: Set some other settings (with sudo)
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items:
    - domain: "/Library/Preferences/com.apple.loginwindow"
      key: "RetriesUntilHint"
      type: "int"
      value: 0
    - domain: "/Library/Preferences/.GlobalPreferences.plist"
      key: "AppleInterfaceTheme"
      type: "string"
      value: "Dark"
    - domain: "/Library/Preferences/SystemConfiguration/com.apple.smb.server"
      key: "NetBIOSName"
      type: "string"
      value: "{{ hostname }}"
  become: yes
